### ISSUE TITLE
Error in "Additional Reports > plugins & content type"

### ISSUE THREAD

**Issue by instruccionesaldorso** [Apen/additional_reports#47] opened 2024-03-27 08:39 UTC
Using latest version for the extension: 3.4.7.
In TYPO3 11.5.36, backend module "Additional Reports > plugins & content type" returns an error:

```
(1/1) TypeError
TYPO3\CMS\Core\Utility\PathUtility::hasProtocolAndScheme(): Argument #1 ($path) must be of type string, null given, called in /var/www/html/vendor/typo3/cms-core/Classes/Utility/PathUtility.php on line 53
```

**Comment by Apen** [comment] 2024-04-09 12:48
It seems that an extension provide an empty path. Could determine which extension throw this error?

**Comment by instruccionesaldorso** [comment] 2024-04-11 05:18
@Apen I found out where the problem lies: https://github.com/Apen/additional_reports/blob/master/Classes/Utility.php#L287-L291

```
if (str_contains($icon['options']['source'], 'EXT:')) {
  $infos['iconext'] = PathUtility::getPublicResourceWebPath($icon['options']['source']);
} else {
  $infos['iconext'] = PathUtility::getAbsoluteWebPath($icon['options']['source']);
}
```

The extension only takes care of `['options']['source']` attribute for every icon defined.
But in TYPO3 11.5, notice that FontAwesome icons may have an `['options']['name']` attribute (not `source`).
The else section should take care of this user case as well.
Even if TYPO3 12.4 dropped FontAwesome icons' support (see here: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98089-RemovedFontAwesome.html), this is still possible through this composer package: https://packagist.org/packages/friendsoftypo3/fontawesome-provider

Defining in a custom extension, `Configuration/Icons.php` file like this:

```
<?php

return [
    'tx-boilerplate-pricing' => [
        'provider' => \FriendsOfTYPO3\FontawesomeProvider\Imaging\IconProvider\FontawesomeIconProvider::class,
        'name' => 'dollar',
    ],
];
```

causes  "Additional Reports > plugins & content type" to fail.

**Comment by Mercutio42** [comment] 2024-06-06 08:18
Hi there,

if you are using the MASK extension, it will not work as well as the $icon['options'] do not return 'name' nor 'source'. Might need a more general approach.
Best regards

**Comment by Apen** [comment] 2024-07-05 09:02
I cannot reproduce easily this setup, could you provide me a text extension that thow this bug? Thanks

**Comment by Apen** [comment] 2024-12-10 14:49
I close this since 11 is not maintained anymore and don't have a correct setup to reproduce this.

**Closed as completed by Apen** 2024-12-10 14:49 UTC
